language: cpp
compiler:
- gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl* libXxf86vm-dev libsdl2-dev libglew-dev libglm-dev libboost-all-dev libboost-program-options-dev autotools-dev
  - autoreconf -i
  - ./configure
install:

branches:
  only:
    - master
notifications:
  email: true
os:
- linux

sudo: true
