Checking src/BoundingBox.cc...
1/13 files checked 7% done
Checking src/Camera.cc...
Checking src/Camera.cc: __APPLE__...
Checking src/Camera.cc: __linux__...
2/13 files checked 15% done
Checking src/CubeAsset.cc...
Checking src/CubeAsset.cc: DEBUG...
Checking src/CubeAsset.cc: __APPLE__...
Checking src/CubeAsset.cc: __linux__...
3/13 files checked 23% done
Checking src/DiamondAsset.cc...
Checking src/DiamondAsset.cc: DEBUG...
Checking src/DiamondAsset.cc: __APPLE__...
Checking src/DiamondAsset.cc: __linux__...
4/13 files checked 30% done
Checking src/GameAsset.cc...
Checking src/GameAsset.cc: __APPLE__...
Checking src/GameAsset.cc: __linux__...
5/13 files checked 38% done
Checking src/GameAssetManager.cc...
Checking src/GameAssetManager.cc: __APPLE__...
Checking src/GameAssetManager.cc: __linux__...
6/13 files checked 46% done
Checking src/GameWorld.cc...
Checking src/GameWorld.cc: __APPLE__...
Checking src/GameWorld.cc: __linux__...
7/13 files checked 53% done
Checking src/GrassAsset.cc...
Checking src/GrassAsset.cc: DEBUG...
Checking src/GrassAsset.cc: __APPLE__...
Checking src/GrassAsset.cc: __linux__...
8/13 files checked 61% done
Checking src/GroundAsset.cc...
Checking src/GroundAsset.cc: DEBUG...
Checking src/GroundAsset.cc: __APPLE__...
Checking src/GroundAsset.cc: __linux__...
9/13 files checked 69% done
Checking src/LeavesAsset.cc...
Checking src/LeavesAsset.cc: DEBUG...
Checking src/LeavesAsset.cc: __APPLE__...
Checking src/LeavesAsset.cc: __linux__...
10/13 files checked 76% done
Checking src/PyramidAsset.cc...
Checking src/PyramidAsset.cc: DEBUG...
Checking src/PyramidAsset.cc: __APPLE__...
Checking src/PyramidAsset.cc: __linux__...
11/13 files checked 84% done
Checking src/PythonBind.cc...
Checking src/PythonBind.cc: __APPLE__...
Checking src/PythonBind.cc: __linux__...
12/13 files checked 92% done
Checking src/main.cc...
Checking src/main.cc: __APPLE__...
Checking src/main.cc: __linux__...
13/13 files checked 100% done
