Checking src/BoundingBox.cc...
1/13 files checked 7% done
Checking src/Camera.cc...
2/13 files checked 15% done
Checking src/CubeAsset.cc...
3/13 files checked 23% done
Checking src/DiamondAsset.cc...
4/13 files checked 30% done
Checking src/GameAsset.cc...
5/13 files checked 38% done
Checking src/GameAssetManager.cc...
6/13 files checked 46% done
Checking src/GameWorld.cc...
7/13 files checked 53% done
Checking src/GrassAsset.cc...
8/13 files checked 61% done
Checking src/GroundAsset.cc...
9/13 files checked 69% done
Checking src/LeavesAsset.cc...
10/13 files checked 76% done
Checking src/PyramidAsset.cc...
11/13 files checked 84% done
Checking src/PythonBind.cc...
12/13 files checked 92% done
Checking src/main.cc...
13/13 files checked 100% done
